[[redirects]]
  from = "https://ariel-landini.netlify.com/*"
  to = "https://landiniarielarq.com.ar/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/pagina-no-encontrada/index.html"
  status = 404
